package com.quzzar.craftmeta.tags;

public enum InvDataTag {

	ANVIL_GUI,
	DOM_CHUNK_SETTINGS_INTRO,
	DOM_CHUNK_SETTINGS_PLAYER,
	DOM_SETTINGS,
	DOM_UPGRADES,
	DISABLED,
	CHARACTER_CREATION_SKIN_SELECT,
	
	MACHINE_STRUCTURE,
	MACHINE_INV_TAG;
	
}
